### PR TITLE
Add client side DrbMessage#load checks

### PR DESCRIPTION
**Pull request by agrare**
Catch TypeError and Packet too large exceptions and print out the full buffer.  This is similar to the server side checks added by https://github.com/ManageIQ/vmware_web_service/pull/17 but on the client side.

Example:
```
TypeError: TypeError: incompatible marshal file format (can't be read) format version 4.8 required; 60.60 0x00000000  04 08 75 3a 13 44 52 62 3a 3a 44 52 62 4f 62 6a  ..u:.DRb::DRbObj
0x00000010  65 63 74 31 04 08 5b 07 49 22 1c 64 72 75 62 79  ect1..[.I".druby
0x00000020  3a 2f 2f 31 32 37 2e 30 2e 30 2e 31 3a 34 30 33  ://127.0.0.1:403
0x00000030  30 33 06 3a 06 45 54 6c 2b 08 d0 e0 9a e0 ad 2a  03.:.ETl+.��.��*

	from /home/agrare/workspace/redhat/manageiq/plugins/vmware_web_service/lib/VMwareWebService/MiqVimDrbDebug.rb:29:in `rescue in block in load'
	from /home/agrare/workspace/redhat/manageiq/plugins/vmware_web_service/lib/VMwareWebService/MiqVimDrbDebug.rb:35:in `block in load'
	from /usr/lib/ruby/2.3.0/sync.rb:234:in `block in sync_synchronize'
	from /usr/lib/ruby/2.3.0/sync.rb:231:in `handle_interrupt'
	from /usr/lib/ruby/2.3.0/sync.rb:231:in `sync_synchronize'
	from /home/agrare/workspace/redhat/manageiq/plugins/vmware_web_service/lib/VMwareWebService/MiqVimDrbDebug.rb:20:in `load'
	from /usr/lib/ruby/2.3.0/drb/drb.rb:642:in `recv_reply'
	from /usr/lib/ruby/2.3.0/drb/drb.rb:941:in `recv_reply'
	from /usr/lib/ruby/2.3.0/drb/drb.rb:1254:in `send_message'
	from /usr/lib/ruby/2.3.0/drb/drb.rb:1142:in `block (2 levels) in method_missing'
	from /usr/lib/ruby/2.3.0/drb/drb.rb:1229:in `open'
	from /usr/lib/ruby/2.3.0/drb/drb.rb:1141:in `block in method_missing'
	from /usr/lib/ruby/2.3.0/drb/drb.rb:1160:in `with_friend'
	from /usr/lib/ruby/2.3.0/drb/drb.rb:1140:in `method_missing'
	from /home/agrare/workspace/redhat/manageiq/plugins/vmware_web_service/lib/VMwareWebService/MiqVimBroker.rb:419:in `getMiqVim'
	from /home/agrare/workspace/redhat/manageiq/plugins/vmware_web_service/lib/VMwareWebService/miq_fault_tolerant_vim.rb:188:in `_connect_with_broker'
	from /home/agrare/workspace/redhat/manageiq/plugins/vmware_web_service/lib/VMwareWebService/miq_fault_tolerant_vim.rb:174:in `block in _connect'
	from /home/agrare/workspace/redhat/manageiq/plugins/vmware_web_service/lib/VMwareWebService/miq_fault_tolerant_vim.rb:86:in `_execute_with_broker'
	from /home/agrare/workspace/redhat/manageiq/plugins/vmware_web_service/lib/VMwareWebService/miq_fault_tolerant_vim.rb:75:in `_execute'
	from /home/agrare/workspace/redhat/manageiq/plugins/vmware_web_service/lib/VMwareWebService/miq_fault_tolerant_vim.rb:172:in `_connect'
	from /home/agrare/workspace/redhat/manageiq/plugins/vmware_web_service/lib/VMwareWebService/miq_fault_tolerant_vim.rb:29:in `initialize'
```

https://bugzilla.redhat.com/show_bug.cgi?id=1385038

### CODE REVIEW

**Comment by agrare** [comment]
I added the `DRb::DRbMessage#load` method without modification so that it was easier to see what was changed: https://github.com/ManageIQ/vmware_web_service/pull/20/commits/478af662d7ff1f2568ed7567de941b473d885347#diff-3d31cccfe722fbfd2f65606ec112c495

**Comment by Fryguy** [comment]
which version of Ruby did you copy this from...I'm just concerned that we will replace DRb with an old/wrong version 😕

**Comment by agrare** [comment]
2.3.something, I can compare across the versions we support.

**Comment by agrare** [comment]
@Fryguy so there were only two commits to that method since ruby 2.0.0 and one was a revert of the other a few days later:
```
git log -L572,603:lib/drb/drb.rb v2_0_0_0..trunk


commit 7b8986f44567df30eb98f3c0928dfa175472b783
Author: usa <usa@b2dd03c8-39d4-4d8f-98ff-823fe69b080e>
Date:   Tue Nov 10 03:08:41 2015 +0000

    * lib/drb/drb.rb: revert r52442 because it was for debugging, and after this
      target problem was misteriously disappeared.
    
    
    git-svn-id: svn+ssh://ci.ruby-lang.org/ruby/trunk@52515 b2dd03c8-39d4-4d8f-98ff-823fe69b080e

diff --git a/lib/drb/drb.rb b/lib/drb/drb.rb
--- a/lib/drb/drb.rb
+++ b/lib/drb/drb.rb
@@ -572,32 +572,32 @@
         str = soc.read(sz)
       rescue
-        raise(DRbConnError, $!.message + " peer: #{soc.peeraddr[2]}:#{soc.peeraddr[1]}, sz: #{sz}", $!.backtrace)
+        raise(DRbConnError, $!.message, $!.backtrace)
       end
       raise(DRbConnError, 'connection closed') if str.nil?
       raise(DRbConnError, 'premature marshal format(can\'t read)') if str.size < sz

commit c457e91a8dd07a38974fb4f27c1ec6fb57dd1395
Author: usa <usa@b2dd03c8-39d4-4d8f-98ff-823fe69b080e>
Date:   Wed Nov 4 03:13:20 2015 +0000

    * lib/drb/drb.rb: add debug information for mswin CI.  this change will be reverted later.
    
    
    git-svn-id: svn+ssh://ci.ruby-lang.org/ruby/trunk@52442 b2dd03c8-39d4-4d8f-98ff-823fe69b080e

diff --git a/lib/drb/drb.rb b/lib/drb/drb.rb
--- a/lib/drb/drb.rb
+++ b/lib/drb/drb.rb
@@ -572,32 +572,32 @@
         str = soc.read(sz)
       rescue
-        raise(DRbConnError, $!.message, $!.backtrace)
+        raise(DRbConnError, $!.message + " peer: #{soc.peeraddr[2]}:#{soc.peeraddr[1]}, sz: #{sz}", $!.backtrace)
       end
       raise(DRbConnError, 'connection closed') if str.nil?
       raise(DRbConnError, 'premature marshal format(can\'t read)') if str.size < sz
```

**Comment by simaishi** [comment]
Fine backport (to manageiq-gems-pending) details:

```
$ git log -1
commit 6215fa1c0e249c28caf9f38db18559ad751d73fd
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Oct 24 09:27:04 2017 -0400

    Merge pull request #20 from agrare/drb_client_side_debugging
    
    Add client side DrbMessage#load checks
    (cherry picked from commit 14731a6bfa74e115db6da9243f56fff738359a22)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1481378
```

**Comment by simaishi** [comment]
Euwe backport (to manageiq repo) details:

```
$ git log -1
commit af41ba7fdc49aa6feb8a07d94dd6d3d0a381ba46
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Oct 24 09:27:04 2017 -0400

    Merge pull request #20 from agrare/drb_client_side_debugging
    
    Add client side DrbMessage#load checks
    (cherry picked from commit 14731a6bfa74e115db6da9243f56fff738359a22)
```

**Pull request merged**
