### PR TITLE
Add marshal version and DRb message size checks

### PR DESCRIPTION
**Pull request by agrare**
Add diagnostic code to dump out the buffer and object sent from the broker if either the DRbMessage size or Marshal version are invalid.

Some errors which have been seen are:
```
Error: [incompatible marshal file format (can't be read)
        format version 4.8 required; 0.0 given] 
[----] E, [2017-07-13T16:51:38.667163 #28357:a4798c] ERROR -- : Q-task_id([miq_provision_509000000041948]) /opt/rh/cfme-gemset/gems/activesupport-5.0.0.1/lib/active_support/core_ext/marshal.rb:4:in `load' 
/opt/rh/cfme-gemset/gems/activesupport-5.0.0.1/lib/active_support/core_ext/marshal.rb:4:in `load' 
/var/www/miq/vmdb/config/initializers/marshal_autoloader.rb:3:in `load' 
/opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:593:in `block in load'
/opt/rh/rh-ruby22/root/usr/share/ruby/sync.rb:233:in `block in sync_synchronize'
/opt/rh/rh-ruby22/root/usr/share/ruby/sync.rb:230:in `handle_interrupt'
/opt/rh/rh-ruby22/root/usr/share/ruby/sync.rb:230:in `sync_synchronize'
/opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:589:in `load' 
/opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:640:in `recv_reply'
/opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:940:in `recv_reply'
/opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1254:in `send_message'
/opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1142:in `block (2 levels) in method_missing'
/opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1229:in `open' 
/opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1141:in `block in method_missing'
/opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1160:in `with_friend'
/opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:1140:in `method_missing'
/var/www/miq/vmdb/gems/pending/VMwareWebService/MiqVimBroker.rb:417:in `getMiqVim'
/var/www/miq/vmdb/gems/pending/util/miq_fault_tolerant_vim.rb:187:in `_connect_with_broker'
/var/www/miq/vmdb/gems/pending/util/miq_fault_tolerant_vim.rb:173:in `block in _connect'
/var/www/miq/vmdb/gems/pending/util/miq_fault_tolerant_vim.rb:85:in `_execute_with_broker'
/var/www/miq/vmdb/gems/pending/util/miq_fault_tolerant_vim.rb:74:in `_execute'
/var/www/miq/vmdb/gems/pending/util/miq_fault_tolerant_vim.rb:171:in `_connect'
/var/www/miq/vmdb/gems/pending/util/miq_fault_tolerant_vim.rb:28:in `initialize'
/var/www/miq/vmdb/app/models/mixins/vim_connect_mixin.rb:22:in `new'
/var/www/miq/vmdb/app/models/mixins/vim_connect_mixin.rb:22:in `connect'
/var/www/miq/vmdb/app/models/mixins/vim_connect_mixin.rb:35:in `with_provider_connection'
/var/www/miq/vmdb/app/models/mixins/provider_object_mixin.rb:5:in `with_provider_connection'
```

and

```
MIQ(MiqGenericWorker::Runner#clean_broker_connection) MIQ(MiqGenericWorker::Runner) Releasing any broker connections for pid: [28398], ERROR: too large packet 67654656
```

https://bugzilla.redhat.com/show_bug.cgi?id=1385038

### CODE REVIEW

**Comment by agrare** [comment]
Example error messages in vim.log:

If the marshal version doesn't match:
```
[----] E, [2017-07-18T15:08:25.229284 #30907:2ae6a1c8f0d4] ERROR -- : Marshal version mismatch: expected: [4, 8] got: [4, 12]
[----] E, [2017-07-18T15:08:25.229323 #30907:2ae6a1c8f0d4] ERROR -- : object: nil
[----] E, [2017-07-18T15:08:25.229388 #30907:2ae6a1c8f0d4] ERROR -- : buffer:
0x00000000  00 00 00 0c 04 0c 20 20                          ......  

[----] E, [2017-07-18T15:08:25.229514 #30907:2ae6a1c8f0d4] ERROR -- : caller:
/usr/lib/ruby/2.3.0/drb/drb.rb:614:in `send_request'
/usr/lib/ruby/2.3.0/drb/drb.rb:926:in `send_request'
/usr/lib/ruby/2.3.0/drb/drb.rb:1253:in `send_message
```

If the DRbMessage size is greater than the `@load_limit`
```
[----] E, [2017-07-18T15:19:28.636313 #1113:2b15819bb0d8] ERROR -- : DRb packet size too large: 3
[----] E, [2017-07-18T15:19:28.636340 #1113:2b15819bb0d8] ERROR -- : object: nil
[----] E, [2017-07-18T15:19:28.636380 #1113:2b15819bb0d8] ERROR -- : buffer:
0x00000000  ff ff ff ff 04 08 30                             ......0
```

**Comment by simaishi** [comment]
Darga backport (to manageiq repo) details:

```
$ git log -1
commit 51c0583e5770880e9ec0c0eb8cd685929eb777bc
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Jul 18 15:21:35 2017 -0400

    Merge pull request #17 from agrare/bz_1385038_drb_marshal_verification
    
    Add marshal version and DRb message size checks
    (cherry picked from commit 2e03c3bbb8e89ed6a9d027c69c1c67b54c4c3300)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1472481
```

**Comment by simaishi** [comment]
Fine backport (to manageiq-gems-pending repo) details:

```
$ git log -1
commit fa6d76f0eb7dc8b8eb878e129e0995520c6700ac
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Jul 18 15:21:35 2017 -0400

    Merge pull request #17 from agrare/bz_1385038_drb_marshal_verification
    
    Add marshal version and DRb message size checks
    (cherry picked from commit 2e03c3bbb8e89ed6a9d027c69c1c67b54c4c3300)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1481378
```

**Comment by simaishi** [comment]
Euwe backport (to manageiq repo) details:

```
$ git log -1
commit e349bcc2e7c267522adde08656b7dfb4edc26841
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Jul 18 15:21:35 2017 -0400

    Merge pull request #17 from agrare/bz_1385038_drb_marshal_verification
    
    Add marshal version and DRb message size checks
    (cherry picked from commit 2e03c3bbb8e89ed6a9d027c69c1c67b54c4c3300)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1481677
```

**Pull request merged**
