### PR TITLE
Revert "Merge pull request #49 from NickLaMuro/an_optimistic_update"

### PR DESCRIPTION
**Pull request by NickLaMuro**
This reverts commit cf35230b875bd68e05c2889e52cb6684114241e1, reversing changes made to 77ea0f8275d91d12677b15d30aef107ed424c5d6.

* * *

My previous witty PR titles and commit messages probably made this PR inevitable...

### CODE REVIEW

**Comment by NickLaMuro** [comment]
@agrare want to merge this, and cut a branch for `0.3-stable` while I then build off master for a `0.4.0` release that reverts this revert?

**Comment by agrare** [comment]
@NickLaMuro how about I create a 0.3.z branch, cut a 0.4.0, then move this PR against the 0.3.z branch?  That way we don't have to revert a revert

**Comment by NickLaMuro** [comment]
@agrare works for me

**Comment by NickLaMuro** [comment]
@agrare Flipped the branch... I think...

does that work?

**Comment by agrare** [comment]
Nice I didn't think you'd be able to change the base branch, yeah looks good to me

**Comment by NickLaMuro** [comment]
> Nice I didn't think you'd be able to change the base branch, yeah looks good to me

Neither did I...

**Comment by agrare** [comment]
Okay released v0.3.3 with this change

**Pull request merged**
