### PR TITLE
Allow Rails 5.1

### PR DESCRIPTION
**Pull request by chrisarcand**
For https://github.com/ManageIQ/manageiq/issues/15036

### CODE REVIEW

**Comment by chrisarcand** [comment]
@miq-bot assign @agrare

**Comment by agrare** [comment]
@chrisarcand I assume you'll need a new gem version?

**Comment by chrisarcand** [comment]
@agrare Yeah looks like it. 💙

**Comment by agrare** [comment]
@chrisarcand `v0.2.1` pushed to rubygems https://rubygems.org/gems/vmware_web_service/versions/0.2.1

**Pull request merged**
